=== prendess/SEW/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="origen" />
				<xs:element ref="puntos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="xs:string" />

	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="fecha" type="xs:date" />

	<xs:element name="hora" type="xs:time" />

	<xs:element name="vueltas" type="xs:positiveInteger" />

	<xs:element name="localidad" type="xs:string" />

	<xs:element name="pais" type="xs:string" />

	<xs:element name="patrocinador" type="xs:string" />

	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="referencia" type="xs:string" minOccurs="3" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="fotografias">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="fotografia" minOccurs="1" maxOccurs="5" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

	<xs:element name="fotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ruta" />
				<xs:element ref="descripcion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ruta" type="xs:string" />

	<xs:element name="descripcion" type="xs:string" />

	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="video" minOccurs="1" maxOccurs="3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="video">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ruta" />
				<xs:element ref="descripcion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudGeo" />
				<xs:element ref="latitudGeo" />
				<xs:element ref="altitudGeo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="longitudGeo" type="xs:decimal" />

	<xs:element name="latitudGeo" type="xs:decimal" />

	<xs:element name="altitudGeo" type="xs:decimal" />

	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="puntoFinal" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="puntoFinal">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudGeo" />
				<xs:element ref="latitudGeo" />
				<xs:element ref="altitudGeo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="sector" type="xs:positiveInteger" />

	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tiempo" type="xs:duration" />

	<xs:element name="clasificacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="posicion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="posicion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="puesto" />
				<xs:element ref="nombre" />
				<xs:element ref="puntosMundial" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="puesto" type="xs:positiveInteger" />

	<xs:element name="puntosMundial" type="xs:integer" />

</xs:schema>

=== prendess/SEW/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>Silverstone</nombre>
    <longitud unidad="m">5901</longitud>
    <anchura unidad="m">12</anchura>
    <fecha>2025-05-25</fecha>
    <hora>14:00:00</hora>
    <vueltas>20</vueltas>
    <localidad>Towcester</localidad>
    <pais>Reino Unido</pais>
    <patrocinador>Tissot</patrocinador>
    <referencias>
        <referencia>https://es.wikipedia.org/wiki/Circuito_de_Silverstone</referencia>
        <referencia>https://www.silverstone.co.uk/</referencia>
        <referencia>https://www.dazn.com/es-ES/news/motor/circuito-de-silverstone-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-de-gran-bretana-del-mundial-de-f1-y-motogp/je8dn5v9wixy1oma2gslxrqcl</referencia>
    </referencias>
    <fotografias>
        <fotografia>
            <ruta>multimedia/vista-aerea.jpg</ruta>
            <descripcion>Vista aérea del circuito de Silverstone</descripcion>
        </fotografia>
        <fotografia>
            <ruta>multimedia/instalaciones.jpg</ruta>
            <descripcion>Detalle de las instalaciones principales del circuito</descripcion>
        </fotografia>
        <fotografia>
            <ruta>multimedia/map.jpg</ruta>
            <descripcion>Ubicación del circuito de Silverstone en el mapa de Reino Unido</descripcion>
        </fotografia>
    </fotografias>
    <videos>
        <video>
            <ruta>multimedia/silverstone-trailer.mp4</ruta>
            <descripcion>Resumen del GP de Silverstone 2025 de MotoGP</descripcion>
        </video>
    </videos>
    <origen>
        <longitudGeo>-1.02228</longitudGeo>
        <latitudGeo>52.06925</latitudGeo>
        <altitudGeo>116</altitudGeo>
    </origen>
    <puntos>
        <punto>
            <distancia unidad="m">287.92</distancia>
            <puntoFinal>
                <longitudGeo>-1.01967</longitudGeo>
                <latitudGeo>52.07128</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">71.42</distancia>
            <puntoFinal>
                <longitudGeo>-1.01864</longitudGeo>
                <latitudGeo>52.07134</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">135.87</distancia>
            <puntoFinal>
                <longitudGeo>-1.01665</longitudGeo>
                <latitudGeo>52.07122</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">95.46</distancia>
            <puntoFinal>
                <longitudGeo>-1.01542</longitudGeo>
                <latitudGeo>52.07162</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">164.17</distancia>
            <puntoFinal>
                <longitudGeo>-1.01356</longitudGeo>
                <latitudGeo>52.07254</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">32.41</distancia>
            <puntoFinal>
                <longitudGeo>-1.01311</longitudGeo>
                <latitudGeo>52.07247</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">121.10</distancia>
            <puntoFinal>
                <longitudGeo>-1.01249</longitudGeo>
                <latitudGeo>52.07145</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">30.98</distancia>
            <puntoFinal>
                <longitudGeo>-1.01203</longitudGeo>
                <latitudGeo>52.07147</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">90.81</distancia>
            <puntoFinal>
                <longitudGeo>-1.01156</longitudGeo>
                <latitudGeo>52.07224</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">91.25</distancia>
            <puntoFinal>
                <longitudGeo>-1.01145</longitudGeo>
                <latitudGeo>52.07306</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">361.57</distancia>
            <puntoFinal>
                <longitudGeo>-1.01534</longitudGeo>
                <latitudGeo>52.07526</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>1</sector>
        </punto>
        <punto>
            <distancia unidad="m">313.59</distancia>
            <puntoFinal>
                <longitudGeo>-1.01877</longitudGeo>
                <latitudGeo>52.07713</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">52.07</distancia>
            <puntoFinal>
                <longitudGeo>-1.01954</longitudGeo>
                <latitudGeo>52.07714</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">39.34</distancia>
            <puntoFinal>
                <longitudGeo>-1.02000</longitudGeo>
                <latitudGeo>52.07693</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">99.40</distancia>
            <puntoFinal>
                <longitudGeo>-1.02024</longitudGeo>
                <latitudGeo>52.07606</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">42.49</distancia>
            <puntoFinal>
                <longitudGeo>-1.02075</longitudGeo>
                <latitudGeo>52.07581</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">52.80</distancia>
            <puntoFinal>
                <longitudGeo>-1.02148</longitudGeo>
                <latitudGeo>52.07595</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">46.58</distancia>
            <puntoFinal>
                <longitudGeo>-1.02168</longitudGeo>
                <latitudGeo>52.07635</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">169.86</distancia>
            <puntoFinal>
                <longitudGeo>-1.02057</longitudGeo>
                <latitudGeo>52.07773</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">66.55</distancia>
            <puntoFinal>
                <longitudGeo>-1.01992</longitudGeo>
                <latitudGeo>52.07816</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">76.77</distancia>
            <puntoFinal>
                <longitudGeo>-1.01897</longitudGeo>
                <latitudGeo>52.07855</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">121.86</distancia>
            <puntoFinal>
                <longitudGeo>-1.01721</longitudGeo>
                <latitudGeo>52.07871</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">336.17</distancia>
            <puntoFinal>
                <longitudGeo>-1.01232</longitudGeo>
                <latitudGeo>52.07897</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">63.18</distancia>
            <puntoFinal>
                <longitudGeo>-1.01148</longitudGeo>
                <latitudGeo>52.07874</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">46.27</distancia>
            <puntoFinal>
                <longitudGeo>-1.01112</longitudGeo>
                <latitudGeo>52.07840</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
            <sector>2</sector>
        </punto>
        <punto>
            <distancia unidad="m">197.35</distancia>
            <puntoFinal>
                <longitudGeo>-1.01041</longitudGeo>
                <latitudGeo>52.07667</latitudGeo>
                <altitudGeo>116</altitudGeo>
            </puntoFinal>
